services:
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    hostname: metabase
    ports:
      - 3000:3000
    environment:
      MB_DB_TYPE: mongodb
      MB_DB_DBNAME: test
      MB_DB_PORT: 27017
      MB_DB_USER: root
      MB_DB_PASS: example
      MB_DB_HOST: mongo
    networks:
      - metanet1
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5
  mongodb:
    image: mongo:latest
    container_name: mongo_db
    hostname: mongo
    volumes:
      - .:/data/db
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    command: ["--auth","--bind_ip_all"]
    networks:
      - metanet1
networks:
  metanet1:
    driver: bridge